feature: implement tasks file storage
desyatov-student/java-kanban pull request #4
Opened 2024-03-15 20:17 UTC by desyatov-student

2024-03-17 14:31 UTC, TomattmanYandex requested changes
Привет, хочу сразу сказать, эта работа это нечто, нечто в плохом смысле этого слова
Все слишком запутано, нагорожено много чего, непонятно зачем, усложнение на усложнении, 
Обычно изменение по этой работе, это несколько файлов
новый таск менеджер, новое перечисление для типов, новый класс конвертер
все остальное, это изменение модификаторов доступа в существующих классах и какие то минимальные исправления соответствующие новым требованиям.
Тут же столько всего, непонятные связи между классами, сами классы непонятно какие и для чего (как минимум на этот этапе)

Вот тут я расписываю почему важно исполнять задания как написано, и не стоит переусложнять.
У вас есть программа по которой вы следуете, где шаг за шагом вы изучаете новые вещи и новые подходы. И задание каждого спринта, это задание на закрепление и понимание того, что вы прошли. Переусложняя можно пропустить что то важное, и следовательно упустить какой то важный опыт или важный момент. А со стороны проверяющего - у нас есть чек листы на проверку каждой работы, и мы им следуем, и если пойти по нему, то как бы хороша этот проект не выполнял поставленную задачу
Самый простой пример из чек листа к данной работе
"Должен быть реализован класс FileBackedTasksManager как наследник от InMemoryTasksManager" (кстати в задании конкретна указана структура классов)
Я не могу найти класс FileBackedTasksManager я не могу найти класс InMemoryTasksManager хотя я вижу что в ветке main он есть, а значит он во что то переименован и поэтому все, работа не принята, основная задача не выполнена, дальше смотреть не вижу смысла.

Выпишу отдельно:
Работа не принята потому что нету соответствия структуре классов в задании. (На следующей итерации я не поленюсь и проверю чтобы данная работа так же соответствовала требованиям предыдущих заданий)

Теперь добавлю общие моменты которые я заметил, которые можно/надо улучшить, которые я заметил в коде
1) структура пакетов
следует ее упростить и упорядочить, например обычно моделями называют те классы которые являются отражением объектов с которыми мы работаем, в этом случае самые близкие это классы Entity. В пакете с ними обычно хранят так же классы от которых они зависят, например перечисления использующиеся в них
TaskContatiner это не модель (это даже по названию понятно)
мапперы это тоже не модели, это сервисы, которые преобразуют модели, следовательно их лучше хранить в пакете service.mapper
2) имена классов
некоторые стоит упростить, например EpicEntity это ключевой объект эпика, и хранится он уже в пакете entity если оставить имя просто Epic то код станет лаконичнее и понятнее, а вот уже всякие Dto стоит так и именовать EpicDto  чтобы просто взглянув на переменную мы понимали, что это не сам эпик а его дтошка
BaseTaskEntity это по сути такой же самостоятельный класс как и сабтаск и эпик, следовательно из него можно убрать приписку в начале что это Base потому что зачем она там, чтобы каждый раз когда мы работали с ним, помнили это это базовый класс? Так а зачем это нужно?
3) модификаторы доступа 
вы их уже изучили, и теперь они  обязательны, даже если хочешь оставить модификатор по умолчанию, то его надо прописать, но обычно данные мы максимально закрываем следовательно надо иметь аргументы почем используется именно он
4) тесты и их пакеты
обычно тесты имеют точно такую же структуру пакетов как и основной код, и если тестируешь класс ru.praktikum.kanban.service.impl.HistoryManagerImpl то его тест хранится в папке test/java в пакете  ru.praktikum.kanban.service.impl
5) именование тестовых методов
обычно тестовый метод тестирует поведение одного конкретного метода и имя этого метода стоит отобразить в имени тестового метода
теперь по именованию самих тестовых методов,
рекомендуют делать составное имя из трех частей
имя тестируемого метода, что должно произойти, при каких условиях
иногда третью часть можно не добавлять
и разделяют их обычно либо словами Should и When 
либо нижними подчеркиваниями
я рекомендую вариант с нижними подчеркиваниями ибо он нагляднее разделяет части и понимать становится проще
пример
tryMap_throwIllegalArgumentException_abstractMapperHasNoClassAndNoFunction
tryMapShouldThrowIllegalArgumentExceptionWhenAbstractMapperHasNoClassAndNoFunction
специально нашел тестовый метод с длиннющим именем, для наглядности
6) структура тестовых методов
обычно для тестовых методов рекомендую структуру из трех частей, которые очень часто разделяют комментариями в коде
public testMethod() {
  //given
  код для подготовки тестовых данных
  //when
  вызов того что тестируем
  //then 
  проверка результатов
}

P.S. вот тебе мем 
https://media.licdn.com/dms/image/C4E22AQF11m8gWTQmXw/feedshare-shrink_800/0/1666542528706?e=2147483647&v=beta&t=BkY9VcdKSOpw7yf7Iqpi_7ykWdScs0ICwmtoE619jwc
а так как вы учитесь, то какой вариант лучше?

2024-03-18 11:12 UTC, desyatov-student commented
Привет. благодарю что потратил столько своего времени чтобы все подробно описать 👍. Давай тогда попорядку будем разбираться с этим.

0. Я намернно избавился от FileBackedTasksManager, InMemoryTasksManager. В место этого теперь есть TasksManagerImpl. Почему так: я считаю что за хранение данных и способе их хранения отвечает репозиторий. Вчера был в памяти, сегодня в файле на диске, завтра будет БД. Способ хранения не должен влиять на TasksManager. Я разделил ответственность (принцип S).  Для хранения я сделал 2 репозитория: InMemoryTaskRepository и FileBackedTaskRepository.  В FileBackedTaskRepository есть сущность для непосредтсвенной записи и чтения с диска TaskFileStorage. В TaskFileStorage есть writer и reader для CSV (Если завтра появится JSON смогу быстро заменить).
Сделал Названия Task, Epic, Subtask убрал Base. В Остальных сущностях тоже убрал Base.
Структуру папок для основного приложения и тестов я изменил.

Давай пока начнем с этого. Про название методов в тестах: буду исправлять. Остальные пункты тоже посмотрю.

2024-03-19 11:37 UTC, TomattmanYandex requested changes
Привет. Я понимаю, ты хочешь сделать как лучше, но требования всегда превыше всего.  в реальных проектах есть возможность обсуждать технические моменты и договариваться, это же учебный проект, и тут есть задание, и оно должно быть выполнено. Я не сторонник следовать ему досконально, шаг в шаг, и если код работает как надо, структурирован и понятен то сильно не придираюсь. 
Но тут:
1) нету структуры, которая необходима по заданию
2) код слишком запутан чтобы легко его понимать

Повторюсь в тексте задания сказано 
"Создайте класс FileBackedTaskManager. В нём вы будете прописывать логику автосохранения в файл. "  В проекте нету класса FileBackedTaskManager следовательно я даже не понимаю откуда мне начинать проверять. И повторюсь, когда он будет, я пройдусь по требованиям предыдущих работ и так же проверю чтобы им соответствовало. Потому, что я вижу что класс InMemoryTaskManager удален

я что то прокомментировал, но я даже не уверен что я прокомментировал то что надо

теперь по твоим комментам к пул реквесту
да за хранение и способе хранения данных отвечает репозиторий, все правильно, хочешь его оставить, оставляй, 
способ хранения не должен влиять на таск менеджер, да обычно не должен, но сейчас у вас в задании что должен быть таск менеджер отвечающий за хранение в памяти таск менеджер отвечающий за хранение в файле, следовательно у тебя может быть пара таск менеджер и таск репозиторий, но для каждого типа будет отдельная пара (а зачем так делать, если можно сделать тогда все в одном классе)
По сути сейчас каждый таск менеджер включает в себя роль сервиса и репозитория
для того чтобы была легкая возможность работать с разными типами файлом, можно в файловом менеджер использовать разные ридеры врайтеры (у тебя кажется такое естьб но все равно размазано еще на один файлб обычно как раз таки ерепозиторий и отвечает за считывание/запись в конкретный тип хранилища (он и есть тот сервис который считывает и записывает)

2024-03-19 11:37 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/model/CreateEpic.java
> +package ru.praktikum.kanban.model;
Если это Dto для создания то во первых следует добавить в имя что это dto во вторых dto следует хранить в отдельном пакете от моделей

2024-03-19 11:37 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/model/Task.java
>      private final int id;
Лучше вместо примитивов использовать класс обертку, 
у примитива есть значение по умолчанию, которое может быть валидным значением, у обертки значение по умолчанию null
Если использовать примитив, то ты не всегда сможешь понять, реальное это значение, или значении по умолчанию

2024-03-19 11:37 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/model/TaskDto.java
> -package ru.praktikum.kanban.model.dto.response;
как уже написал выше, лучше хранить Dto отдельно от моделей

2024-03-19 11:37 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/repository/impl/FileBackedTaskRepository.java
> +    boolean isLoaded = false;
Модификаторы доступа обязательны

2024-03-19 11:37 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/repository/impl/FileBackedTaskRepository.java
> +    public void loadFromFileStorage() {
лучше этот метод сделать приватным и вызывать при создании объекта

2024-03-19 11:37 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +        subtasks.put(subtask.getId(), subtask);
При сохранении сабтаска необходимо обновлять статус соответствующего эпика

2024-03-19 11:37 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +        subtasks.remove(subtaskId);
При удалении сабтаска необходимо обновлять статус соответствующего эпика

2024-03-19 11:37 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +        subtasks.clear();
аналогично с предыдущим

2024-03-19 11:37 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +        epics.remove(epicId);
при удалении эпика необходимо удалять его сабтаски

2024-03-19 11:37 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +        epics.clear();
аналогично с предыдущим

2024-03-19 11:37 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +    protected final HistoryLinkedList history;
тут должен быть менеджер истории а не список

2024-03-19 11:37 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +    public void removeFromHistory(int id) {
такого метода тут быть не должно

2024-03-19 11:37 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +    public void addToHistory(Task task) {
такого метода тут быть не долнжо

2024-03-19 11:37 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/service/backup/TaskFileStorage.java
> +    Path filePath;
модификаторы доступа

2024-03-19 19:33 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +        subtasks.put(subtask.getId(), subtask);
Репозиторий у меня только для хранения данных. вся логика по вычислению статуса и обновлению эпика происходит в TaskManager:
```Java
@Override
    public SubtaskDto createSubtask(CreateSubtaskDto subtaskDto) {
        Integer epicId = subtaskDto.getEpicId();
        Epic epic = repository.getEpic(epicId);
        if (epic == null) {
            return null;
        }
        Subtask subtask = subtaskMapper.toEntity(getNextTaskId(), subtaskDto);
        subtask.setEpicId(epicId);
        epic.subtasks.add(subtask.getId());

        repository.saveSubtask(subtask);
        updateEpicStatus(epic);

        return subtaskMapper.toDto(subtask);
    }
```

2024-03-19 19:42 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +        subtasks.remove(subtaskId);
Описал выше подробнее что вся логика по вычислению статуса и обновлению тасок происходит в TaskManager

2024-03-19 19:42 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +        subtasks.clear();
Описал выше подробнее что вся логика по вычислению статуса и обновлению тасок происходит в TaskManager

2024-03-19 19:44 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +        epics.remove(epicId);
Описал выше подробнее что вся логика по вычислению статуса и обновлению тасок происходит в TaskManager

2024-03-19 19:50 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +        epics.clear();
Описал выше подробнее что вся логика по вычислению статуса и обновлению тасок происходит в TaskManager

2024-03-19 20:10 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +    protected final HistoryLinkedList history;
Как ты попросил я сделал
`InMemoryTaskManager` 
и
`FileBackedTaskManager`

Схема для хранения в памяти. Аналогично для хранения в файле.

<img width="1033" alt="image" src="https://github.com/desyatov-student/java-kanban/assets/155831414/0a43d6d8-1bb5-4fd7-a406-6d519e00af87">

2024-03-19 20:11 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +    public void removeFromHistory(int id) {
Посмотри схему классов выше. Это репозиторий и он только хранит данные

2024-03-19 20:22 UTC, desyatov-student commented
Начертил схему классов

<img width="645" alt="image" src="https://github.com/desyatov-student/java-kanban/assets/155831414/e3897ca2-676d-469b-bdf8-bb720b408643">

2024-03-20 11:57 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/repository/impl/InMemoryTaskRepository.java
> +    public void removeFromHistory(int id) {
если это репозиторий тасок, то какое он отношение имеет к истории?

2024-03-20 12:24 UTC, TomattmanYandex requested changes
Привет Я оставил минимальный комментарий, что стоит еще поправить.
Ииии....
Поднял в ревьюверском чате вопрос, стоит ли такое вообще принимать, если ответят что можно то приму

2024-03-20 12:24 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/service/impl/Managers.java
Тут стоит добавить метод на получение таск менеджера который работает в памяти

2024-03-20 12:24 UTC, TomattmanYandex commented on src/main/java/ru/praktikum/kanban/service/impl/Managers.java
а еще оставить метод на получение менеджера истории, и в конструктор менеджера тасков, засовывать его из этого метода

2024-03-20 19:33 UTC, desyatov-student commented
> Привет Я оставил минимальный комментарий, что стоит еще поправить. Ииии.... Поднял в ревьюверском чате вопрос, стоит ли такое вообще принимать, если ответят что можно то приму

Если нужно что то еще поправить то давайте обсудим. Я за конструктивный диалог. Главное дайте аргументы кроме того что надо как в ТЗ.

2024-03-20 19:39 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/service/impl/Managers.java
Я вернул метод `getDefaultHistory(HistoryRepository repository)`
Только он будет с параметром. Объясню почему так:
Если будут 2 разных инстанса сущности которая восстанавливает данные из фала они обе полезут в один файл. И восстановятся разные инстансы тасков. В исотрии один экземпляр в менеджере другой. И при изменении например в истории изменения в менеджере не применятся. Должен быть один инстанс таски и в истории и в менеджере

2024-03-26 19:23 UTC, merged