Sprint 8 solution time and duration
desyatov-student/java-kanban pull request #5
Opened 2024-03-29 21:19 UTC by desyatov-student

2024-04-01 06:17 UTC, kriwsha requested changes

2024-04-01 06:17 UTC, kriwsha commented on src/main/java/ru/praktikum/kanban/dto/EpicDto.java
> +            LocalDateTime endTime
У вас время окончания зависит от длительности, а в случае с эпиком еще и от подзадач, поэтому не следует это поле получать снаружи. Это касается не только эпика, но и других сущностей

2024-04-01 06:17 UTC, kriwsha commented on src/main/java/ru/praktikum/kanban/dto/UpdateSubtaskDto.java
> +public class UpdateSubtaskDto extends UpdateTaskDto {
Тут хотелось бы понять мотивацию для создания отдельных сущностей для создания и обновления основных объектов. Если их дальше сохранять в базу данных, то это один и тот же набор полей. При этом может возникнуть путаница, где какой использовать. Судя по архитектуре вашего приложения, вы создаете некий REST API сервис, но у вас с фронта в этом случае будет приходить один и тот же JSON. Я бы все-таки рекомендовал отказаться от лишних классов

2024-04-01 06:17 UTC, kriwsha commented on src/main/java/ru/praktikum/kanban/dto/UpdateTaskDto.java
> +    public boolean isTimeEmpty() {
Если я правильно понимаю, то это внутренняя логика, поэтому следует метод сделать приватным, иначе вы раскрываете внутренние алгоритмы работы, что может спровоцировать появление уязвимостей в вашем приложении

2024-04-01 06:17 UTC, kriwsha commented on src/main/java/ru/praktikum/kanban/model/Task.java
> +    public boolean isTimeEmpty() {
То же самое здесь

2024-04-01 10:19 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/dto/UpdateTaskDto.java
> +    public boolean isTimeEmpty() {
Это нужно для внешней проверки. По ТЗ указано что у некоторых тасков может отсутствовать дата начала. Поэтому чтобы добавлять в приоритетные задачи нужно проверять а есть ли дата

2024-04-01 10:22 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/dto/UpdateSubtaskDto.java
> +public class UpdateSubtaskDto extends UpdateTaskDto {
Есть несколько видов:
Update - только для обновления. Например для эпика можно обновить только название и описание. Остальные полня не нужны и поэтому нет смысла пользователем их вводить
Create - для создания. там не нужно передавать id, Status поэтому там сразу дефолтный
TaskDto то что отдается наружу пользователю и там ничего не меняется

2024-04-01 10:56 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/dto/EpicDto.java
> +            LocalDateTime endTime
Нарисовал схему устройства.  Поле LocalDateTime endTime вычисляемое в модели Task и повторный расчет не обязателен. После этого  Task мапится в TaskDto и чтобы не городить эту логику вычисления которая в эпике отличается я принял решение использовать просто поля для хранения.
<img width="742" alt="image" src="https://github.com/desyatov-student/java-kanban/assets/155831414/d612bb4c-f823-4fc3-bbc0-36dc5de9c0bb">

2024-04-01 11:09 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/dto/UpdateTaskDto.java
> +    public boolean isTimeEmpty() {
Можно конечно убрать и перенести в модель TaskTime

2024-04-01 11:10 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/model/Task.java
> +    public boolean isTimeEmpty() {
Task это внутренняя моделька и наружу не отдается.

2024-04-02 11:37 UTC, kriwsha requested changes

2024-04-02 11:37 UTC, kriwsha commented on src/main/java/ru/praktikum/kanban/dto/EpicDto.java
> +            LocalDateTime endTime
Я логику формирования названий понимаю. Если быть последовательным, то dto как раз не для хранения данных, а для их передачи (все таки, data transfer object). Откуда могут передаваться данные? С клиента. Кто может быть клиентом? Браузер, другое приложение, а может, это вообще будет использовано как библиотека более крупного приложения. Поскольку приложение не содержит контроллеров (проще говоря, извне оно недоступно), и в ТЗ нет упоминания о том, что нужно добавлять эндпойнты, то вероятнее всего, это все таки больше похоже на библиотеку, которую добавят в другой проект и будут использовать для создания более крупного приложения. А теперь представьте, что разработчик того приложения получил первую задачу, видит, что можно проставить поле endTime прямо в конструктор. Зачем разбираться дальше - можно ведь уже поставить. Так будет нарушена логика вашего части.

2024-04-02 11:37 UTC, kriwsha commented on src/main/java/ru/praktikum/kanban/dto/UpdateSubtaskDto.java
> +public class UpdateSubtaskDto extends UpdateTaskDto {
Вы рассуждаете правильно, но как я писал выше, подобная логика характерна для приложений, взаимодействующих с клиентом. TaskManager - это не контроллер, это сервис, управляющий задачами. Причем его логика довольна проста - принимать, сохранять, возвращать. Все описанное должно происходить до поступления объекта в TaskManager. Я понимаю ваше желание сделать приложение более полноценным. Это отлично. Но нас ограничивает ТЗ и архитектура.

2024-04-02 11:37 UTC, kriwsha commented on src/main/java/ru/praktikum/kanban/model/Task.java
> +    public boolean isTimeEmpty() {
А что для вас "наружа"? Вот у вас есть CreateTaskDto, а есть Task. Как другому разработчику понять, что можно использовать, а что нельзя? Есть вариант документации, но у вас код не задокументирован. Есть вариант поиграться с пакетами и модификаторами доступа, но и этого нет. Остается ТЗ и интерфейс TaskManager'а. Но тут возникает проблема - в ТЗ другой разработчик увидит одно, а в интерфейсе другое. Он с этим пойдет к своему лидеру, тот пойдет к вашему лидеру, а ваш лидер придет к вам и спросит, почему в ТЗ написано так, а вы сделали по-другому? Касательно именно этого метода я согласен, что в рамках текущей ситуации оно допустимо, хотя излишне. Если у нас нет startTime, то duration нас вообще не интересует.

2024-04-02 12:05 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/dto/EpicDto.java
> +            LocalDateTime endTime
Хорошо, сделает он эту модель с endtime  и что дальше он с ней может сделать? Может просто локально использовать. Это просто конструктор. А библиотека будет наружу выдавать только готовые модели без возможности изменить. 
Возьмем пример эпик: у него endTime зависит от endTime последнего сабстаска. например 2 сабтаска: с 9:00 продолжительностью 1 час и второй с 15:00 продолжительностью 1 час. получаем начало эпика в 9:00 окончание в 16:00 но (!!!) внимание  продолжительность тасок 2 часа. Значит для эпика нужны разные данные для передачи в конструктор и начало и продолжительность и окончание. Можно конечно только для эпика сделать  а для остальных расчитывать, но зачем усложнение.

По логике расчета я обсуждал с наставником:

<img width="391" alt="image" src="https://github.com/desyatov-student/java-kanban/assets/155831414/7a292662-c5a9-42e3-bbca-955a07b561d4">

2024-04-02 12:07 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/dto/UpdateSubtaskDto.java
> +public class UpdateSubtaskDto extends UpdateTaskDto {
В тз есть модели Task, Epic, Subtask я их сделал. Остальное это уже мои рюшечки. Формально тз соблюдается

2024-04-02 12:16 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/model/Task.java
> +    public boolean isTimeEmpty() {
Документация есть в readme. 
про наружу - я пока не знаю как сделать в джава но можно сделать публичные классы они будут видны в либе, а есть доступные только пакету (либе).  Если есть информация где это глянуть я могу сделать такие ограничения и тогда наружу будут доступны только определенные классы.
Если есть startTime но нет duration тоже нужно учитывать


<img width="997" alt="image" src="https://github.com/desyatov-student/java-kanban/assets/155831414/2594142c-8905-4558-90b0-befedd6a1e5a">

2024-04-02 12:21 UTC, desyatov-student commented
Нужно финализировать что конкретно мне исправлять, иначе долго будет переписка :)

2024-04-02 12:36 UTC, desyatov-student commented
Если бы ТЗ было настолько идеальным то не возникало бы таких вопросов:
<img width="907" alt="image" src="https://github.com/desyatov-student/java-kanban/assets/155831414/52774b2e-03ba-498f-95b7-d645cc581bae">

2024-04-02 12:39 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/dto/EpicDto.java
> +            LocalDateTime endTime
Я на 99.9 уверен что в следующем спринте мы как раз проходим HTTP  и добавим этот контроллер тогда мне ничего не нужно менять. Все уже будет готово. И все модели готовы

2024-04-02 14:00 UTC, desyatov-student commented on src/main/java/ru/praktikum/kanban/model/Task.java
> +    public boolean isTimeEmpty() {
> Касательно именно этого метода я согласен, что в рамках текущей ситуации оно допустимо, хотя излишне.

Проверка на каждое создание и обновление таска для 3-х типов итого 9 использований. Могу в отдельный метод вынести куда нибудь, но для расчета endTime его все равно нужно использовать

2024-04-14 19:27 UTC, merged